services:
  # название сервиса 
  main-app:  
    # указываем путь к .env файлу с переменными окружения
    env_file:
      - ./.env
    
    # собираем образ помощью Dockerfile
    build:
      dockerfile: Dockerfile_main

    # перенаправляем порты
    # используем переменные из .env файла
    ports:
      - "${MAIN_APP_PORT_VM}:${MAIN_APP_PORT}"

    # указываем тома
    volumes:
        # тип тома 
      - type: bind
        # директория на ВМ
        source: ./speeches
        # директория в контейнере
        target: /app_with_counter/speeches
        
        
  # название сервиса 
  counter-app:
    # указываем путь к .env файлу с переменными окружения
    env_file:
      - ./.env
    
    # собираем образ с помощью Dockerfile
    build:
      dockerfile: Dockerfile_counter

    # hostname указывает, на какой хост должны обращаться другие контейнеры в рамках одного проекта, чтобы обратиться к этому сервису.
    hostname: counter
    
    # перенаправляем порты
    # используем переменные из .env файла
    ports:
      - "${COUNTER_APP_PORT_VM}:${COUNTER_APP_PORT}"
    
    
